server: hub-cloud.browserstack.com
user: "pierreedouardmat1"
key: "ypPtsauCEeEzxZTZVUNW"

common_caps:
  build: capybara-browserstack
  browserstack.debug: true
  browserstack.video: false
  name: BS-PEM-[Capybara]-para

browser_caps:
- browser: chrome
-
    device: Samsung Galaxy S9
    realMobile: true
    os_version: 8.0
-
    device: iPhone X
    realMobile: true
    os_version: 11
- browser: internet explorer
- browser: safari
