server: hub-cloud.browserstack.com
user: "pierreedouardmat1"
key: "ypPtsauCEeEzxZTZVUNW"

common_caps:
  build: capybara-browserstack
  browserstack.debug: true
  browserstack.video: false
  name: BS-PEM-[Capybara]-para

browser_caps:
  -
    "os": "Windows"
    "os_version": "10"
    "browser": "Chrome"
    "browser_version": "80.0"
    "resolution": "1024x768"
  -
    "os": "Windows"
    "os_version": "10"
    "browser": "Edge"
    "browser_version": "80.0"
    "resolution": "1024x768"
  -
    "os": "Windows"
    "os_version": "10"
    "browser": "IE"
    "browser_version": "11.0"
    "resolution": "1024x768"
  -
    "device": "iPhone X"
    "realMobile": "true"
    "os_version": "11"
  -
    "device": "iPhone 7"
    "realMobile": "true"
    "os_version": "10"    