server: hub-cloud.browserstack.com
user: "pierreedouardmat1"
key: "ypPtsauCEeEzxZTZVUNW"

common_caps:
  build: capybara-browserstack
  browserstack.debug: true
  name: BS-PEM-[Capybara]

browser_caps:
- browser: chrome
